"""block4 decisions and documents

Revision ID: 250096e3db15
Revises: b61065a83660
Create Date: 2026-09-01 13:20:54.726791
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '250096e3db15'
down_revision: str | None = 'b61065a83660'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_items',
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('covered', sa.Boolean(), nullable=False),
    sa.Column('covered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_items_meeting_id'), 'agenda_items', ['meeting_id'], unique=False)
    op.create_index('ix_agenda_meeting_position', 'agenda_items', ['meeting_id', 'position'], unique=False)
    op.create_table('decisions',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=True),
    sa.Column('agenda_item_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('responsible_id', sa.BigInteger(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.BigInteger(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agenda_item_id'], ['agenda_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_author_id'), 'decisions', ['author_id'], unique=False)
    op.create_index('ix_decisions_meeting', 'decisions', ['meeting_id'], unique=False)
    op.create_index('ix_decisions_org_created', 'decisions', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_decisions_organization_id'), 'decisions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_decisions_responsible_id'), 'decisions', ['responsible_id'], unique=False)
    op.create_index('ix_decisions_search', 'decisions', [sa.literal_column("to_tsvector('russian', title || ' ' || coalesce(details, ''))")], unique=False, postgresql_using='gin')
    op.create_table('documents',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.Column('file_unique_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('meeting_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('decision_id', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('index_status', sa.String(length=16), nullable=False),
    sa.Column('index_error', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_unique_id'), 'documents', ['file_unique_id'], unique=False)
    op.create_index(op.f('ix_documents_index_status'), 'documents', ['index_status'], unique=False)
    op.create_index('ix_documents_meeting', 'documents', ['meeting_id'], unique=False)
    op.create_index('ix_documents_name_trgm', 'documents', ['file_name'], unique=False, postgresql_using='gin', postgresql_ops={'file_name': 'gin_trgm_ops'})
    op.create_index('ix_documents_org_created', 'documents', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index('ix_documents_task', 'documents', ['task_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_table('document_access',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_department_id', sa.BigInteger(), nullable=True),
    sa.Column('granted_by', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'subject_user_id', 'subject_department_id', name='uq_document_access_subject')
    )
    op.create_index(op.f('ix_document_access_document_id'), 'document_access', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_access_subject_user_id'), 'document_access', ['subject_user_id'], unique=False)
    op.create_table('document_texts',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_document_text')
    )
    op.create_index('ix_document_texts_search', 'document_texts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('document_views',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_views_doc_at', 'document_views', ['document_id', 'viewed_at'], unique=False)
    op.create_index(op.f('ix_document_views_user_id'), 'document_views', ['user_id'], unique=False)
    op.create_table('download_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('issued_to', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_to'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_download_token')
    )
    op.create_index('ix_download_tokens_expiry', 'download_tokens', ['expires_at'], unique=False, postgresql_where=sa.text('used_at IS NULL'))
    op.create_index('ix_meetings_search', 'meetings', [sa.literal_column("to_tsvector('russian', title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_tasks_search', 'tasks', [sa.literal_column("to_tsvector('russian', title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_search', table_name='tasks', postgresql_using='gin')
    op.drop_index('ix_meetings_search', table_name='meetings', postgresql_using='gin')
    op.drop_index('ix_download_tokens_expiry', table_name='download_tokens', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_table('download_tokens')
    op.drop_index(op.f('ix_document_views_user_id'), table_name='document_views')
    op.drop_index('ix_document_views_doc_at', table_name='document_views')
    op.drop_table('document_views')
    op.drop_index('ix_document_texts_search', table_name='document_texts', postgresql_using='gin')
    op.drop_table('document_texts')
    op.drop_index(op.f('ix_document_access_subject_user_id'), table_name='document_access')
    op.drop_index(op.f('ix_document_access_document_id'), table_name='document_access')
    op.drop_table('document_access')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index('ix_documents_task', table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index('ix_documents_org_created', table_name='documents')
    op.drop_index('ix_documents_name_trgm', table_name='documents', postgresql_using='gin', postgresql_ops={'file_name': 'gin_trgm_ops'})
    op.drop_index('ix_documents_meeting', table_name='documents')
    op.drop_index(op.f('ix_documents_index_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_unique_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_decisions_search', table_name='decisions', postgresql_using='gin')
    op.drop_index(op.f('ix_decisions_responsible_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_organization_id'), table_name='decisions')
    op.drop_index('ix_decisions_org_created', table_name='decisions')
    op.drop_index('ix_decisions_meeting', table_name='decisions')
    op.drop_index(op.f('ix_decisions_author_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_agenda_meeting_position', table_name='agenda_items')
    op.drop_index(op.f('ix_agenda_items_meeting_id'), table_name='agenda_items')
    op.drop_table('agenda_items')
    # ### end Alembic commands ###
