"""block3 meetings

Revision ID: b61065a83660
Revises: da4a67a2da3c
Create Date: 2026-09-01 08:40:31.203112
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b61065a83660'
down_revision: str | None = 'da4a67a2da3c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_organization_id'), 'rooms', ['organization_id'], unique=False)
    op.create_table('meetings',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('on_behalf_of_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('reschedule_count', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('owner_id'), '='), (sa.text('tstzrange(start_at, end_at)'), '&&'), where=sa.text("status <> 'CANCELLED'"), using='gist', name='excl_meetings_owner_overlap'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['on_behalf_of_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetings_org_start', 'meetings', ['organization_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_meetings_organization_id'), 'meetings', ['organization_id'], unique=False)
    op.create_index('ix_meetings_owner_start', 'meetings', ['owner_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_meetings_start_at'), 'meetings', ['start_at'], unique=False)
    op.create_table('time_quotas',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_department_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_user_id', sa.BigInteger(), nullable=True),
    sa.Column('minutes', sa.SmallInteger(), nullable=False),
    sa.Column('period', sa.String(length=12), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'subject_department_id', 'subject_user_id', name='uq_time_quota_subject')
    )
    op.create_index(op.f('ix_time_quotas_organization_id'), 'time_quotas', ['organization_id'], unique=False)
    op.create_index(op.f('ix_time_quotas_owner_id'), 'time_quotas', ['owner_id'], unique=False)
    op.create_table('meeting_attendance',
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('late_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('marked_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_attendance')
    )
    op.create_index(op.f('ix_meeting_attendance_meeting_id'), 'meeting_attendance', ['meeting_id'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('response', sa.String(length=16), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_participant')
    )
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index('ix_meeting_participants_user', 'meeting_participants', ['user_id', 'meeting_id'], unique=False)
    op.create_table('meeting_ratings',
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('rated_by', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('voice_file_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rated_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'rated_by', name='uq_meeting_rating')
    )
    op.create_index(op.f('ix_meeting_ratings_meeting_id'), 'meeting_ratings', ['meeting_id'], unique=False)
    op.create_table('meeting_requests',
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('initiator_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('over_quota', sa.Boolean(), nullable=False),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('meeting_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_requests_organization_id'), 'meeting_requests', ['organization_id'], unique=False)
    op.create_index('ix_meeting_requests_owner_status', 'meeting_requests', ['owner_id', 'status'], unique=False)
    op.create_table('room_bookings',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    postgresql.ExcludeConstraint((sa.column('room_id'), '='), (sa.text('tstzrange(start_at, end_at)'), '&&'), using='gist', name='excl_room_bookings_overlap'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_bookings_meeting_id'), 'room_bookings', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_room_bookings_room_id'), 'room_bookings', ['room_id'], unique=False)
    op.create_table('slot_holds',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('held_by', sa.BigInteger(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    postgresql.ExcludeConstraint((sa.column('owner_id'), '='), (sa.text('tstzrange(start_at, end_at)'), '&&'), where=sa.text('released_at IS NULL'), using='gist', name='excl_slot_holds_overlap'),
    sa.ForeignKeyConstraint(['held_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['meeting_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slot_holds_expiry', 'slot_holds', ['expires_at'], unique=False, postgresql_where=sa.text('released_at IS NULL'))
    op.create_index(op.f('ix_slot_holds_owner_id'), 'slot_holds', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slot_holds_owner_id'), table_name='slot_holds')
    op.drop_index('ix_slot_holds_expiry', table_name='slot_holds', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_table('slot_holds')
    op.drop_index(op.f('ix_room_bookings_room_id'), table_name='room_bookings')
    op.drop_index(op.f('ix_room_bookings_meeting_id'), table_name='room_bookings')
    op.drop_table('room_bookings')
    op.drop_index('ix_meeting_requests_owner_status', table_name='meeting_requests')
    op.drop_index(op.f('ix_meeting_requests_organization_id'), table_name='meeting_requests')
    op.drop_table('meeting_requests')
    op.drop_index(op.f('ix_meeting_ratings_meeting_id'), table_name='meeting_ratings')
    op.drop_table('meeting_ratings')
    op.drop_index('ix_meeting_participants_user', table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_meeting_attendance_meeting_id'), table_name='meeting_attendance')
    op.drop_table('meeting_attendance')
    op.drop_index(op.f('ix_time_quotas_owner_id'), table_name='time_quotas')
    op.drop_index(op.f('ix_time_quotas_organization_id'), table_name='time_quotas')
    op.drop_table('time_quotas')
    op.drop_index(op.f('ix_meetings_start_at'), table_name='meetings')
    op.drop_index('ix_meetings_owner_start', table_name='meetings')
    op.drop_index(op.f('ix_meetings_organization_id'), table_name='meetings')
    op.drop_index('ix_meetings_org_start', table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_rooms_organization_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
