"""error log and health

Revision ID: da4a67a2da3c
Revises: a1c4e7b9d200
Create Date: 2026-09-01 08:01:46.066248
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'da4a67a2da3c'
down_revision: str | None = 'a1c4e7b9d200'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_log',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('seen_count', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_error_log_fingerprint', 'error_log', ['fingerprint'], unique=False)
    op.create_index('ix_error_log_recent', 'error_log', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_error_log_recent', table_name='error_log')
    op.drop_index('ix_error_log_fingerprint', table_name='error_log')
    op.drop_table('error_log')
    # ### end Alembic commands ###
